<?xml version="1.0" encoding="utf-8"?><Database Name="dataStore" Class="dataStoreDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\dataStore.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dataStoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Weights" Member="Weights">
    <Type Name="Weight">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="range" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Weight_Price" Member="Prices" ThisKey="id" OtherKey="rangeID" Type="Price" />
      <Association Name="Weight_Mail" Member="Mails" ThisKey="id" OtherKey="WeightRange" Type="Mail" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MobileNo" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Customer_Mail" Member="Mails" ThisKey="CustomerID" OtherKey="Customer" Type="Mail" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="StaffID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BranchID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Employee_Mail" Member="Mails" ThisKey="StaffID" OtherKey="StaffID" Type="Mail" />
      <Association Name="Branch_Employee" Member="Branch" ThisKey="BranchID" OtherKey="BranchID" Type="Branch" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.Prices" Member="Prices">
    <Type Name="Price">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rangeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="serviceID" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Member="Price1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Weight_Price" Member="Weight" ThisKey="rangeID" OtherKey="id" Type="Weight" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Service_Price" Member="Service" ThisKey="serviceID" OtherKey="ServiceID" Type="Service" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Services" Member="Services">
    <Type Name="Service">
      <Column Name="ServiceID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ServiceName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Association Name="Service_Price" Member="Prices" ThisKey="ServiceID" OtherKey="serviceID" Type="Price" />
      <Association Name="Service_Mail" Member="Mails" ThisKey="ServiceID" OtherKey="PrefferedService" Type="Mail" />
    </Type>
  </Table>
  <Table Name="dbo.Mails" Member="Mails">
    <Type Name="Mail">
      <Column Name="DeliveryNo" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateRecieved" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="WeightRange" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActualWeight" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="PrefferedService" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DeliverySource" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryDestination" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Customer" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SecretPin" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Remarks" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CollectedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CollectionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Customer_Mail" Member="Customer1" ThisKey="Customer" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Employee_Mail" Member="Employee" ThisKey="StaffID" OtherKey="StaffID" Type="Employee" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Service_Mail" Member="Service" ThisKey="PrefferedService" OtherKey="ServiceID" Type="Service" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Weight_Mail" Member="Weight" ThisKey="WeightRange" OtherKey="id" Type="Weight" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Branch_Mail" Member="Branch" ThisKey="DeliveryDestination" OtherKey="BranchID" Type="Branch" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Branch" Member="Branches">
    <Type Name="Branch">
      <Column Name="BranchID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Branch_Location" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Branch_Employee" Member="Employees" ThisKey="BranchID" OtherKey="BranchID" Type="Employee" />
      <Association Name="Branch_Mail" Member="Mails" ThisKey="BranchID" OtherKey="DeliveryDestination" Type="Mail" />
    </Type>
  </Table>
</Database>